name: RELEASE

on:
  push:
    branches:
      - main

jobs:
  release:
    name: release version
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup package manager
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: install node
        uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          check-latest: true
          node-version-file: '.nvmrc'
      - name: install dependencies
        run: pnpm install
      - name: release version
        run: pnpm exec semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
